### ISSUE TITLE
Can't select effects

### ISSUE THREAD

**Issue by ephur** [lexcast/power-effects#1]
[Enter steps to reproduce:]

1.  Choose - select effect from menu

I see that this error is thrown from the activate-power-mode module, but it does not occur when I don't have power-effects installed (obviously). The first time I was able to select an effect, but on concurrent selections it does not work.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of null

```
At /Users/rich9548/.atom/packages/activate-power-mode/lib/effect-registry.coffee:52

TypeError: Cannot read property 'toggle' of null
    at /packages/activate-power-mode/lib/effect-registry.coffee:52:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
  3x -5:12.1.0 core:backspace (input.hidden-input)
     -5:01.1.0 autocomplete-plus:cancel (input.hidden-input)
     -5:00.1.0 settings-view:open (input.hidden-input)
 25x -4:40 core:backspace (input.hidden-input)
     -1:21.2.0 editor:consolidate-selections (input.hidden-input)
     -1:21.2.0 core:cancel (input.hidden-input)
     -1:19.9.0 editor:consolidate-selections (input.hidden-input)
     -1:19.9.0 core:cancel (input.hidden-input)
     -1:15.1.0 command-palette:toggle (input.hidden-input)
  6x -1:14.4.0 core:backspace (input.hidden-input)
     -1:10.2.0 core:confirm (input.hidden-input)
     -1:10.2.0 activate-power-mode:select-effect (input.hidden-input)
     -0:41.1.0 settings-view:open (input.hidden-input)
     -0:06.8.0 command-palette:toggle (button.btn.icon.enablement.icon-playback-pause)
     -0:03.5.0 core:confirm (input.hidden-input)
     -0:03.5.0 activate-power-mode:select-effect (button.btn.icon.enablement.icon-playback-pause)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
ansible-vault 0.5.2 
ariake-dark-syntax 0.1.3 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-python-virtualenv 0.14.0 
autocomplete-json 5.5.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
gloom 0.6.4 
gruvbox-plus-syntax 1.3.1 
Hydrogen 1.15.0 
intentions 1.1.2 
language-ansible 0.2.1 
language-terraform 0.8.1 
line-ending-converter 1.3.2 
linter 2.1.4 
linter-ansible-linting 1.3.0 
linter-ansible-syntax 1.2.0 
linter-json-lint 0.1.2 
linter-markdown 4.0.1 
linter-python 3.1.2 
linter-terraform-syntax 1.2.0 
linter-ui-default 1.6.0 
linter-vagrant-validate 1.1.0 
linter-write-good 0.9.0 
min-ui 0.0.4 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
power-effects 0.1.0 
python-indent 1.0.2 
python-tools 0.6.9 
zentabs 0.8.8 
```

**Comment by lexcast** [comment]
Hi @ephur 
This always happens for you? I can't reproduce it.

**Comment by ephur** [comment]
Hello! Thanks for following up. I upgraded to 0.2.0 and the problem went away. I'm not sure if related, or something in Atom changed :\ Sorry I didn't create better reproduction steps at the time. Will keep in mind, thanks for looking. Cool plugin to change the effects.

**Comment by lexcast** [comment]
Great @ephur. Nothing has changed about that in this package so not sure what happened. But glad this issue is gone.
